//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpTest.Dados.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CHASSI
    {
        public string COD_CHASSI { get; set; }
        public string TIPO_VEICULO { get; set; }
        public int NUM_PASSAGEIROS { get; set; }
        public Nullable<System.DateTime> DT_CADASTRO { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public string COR { get; set; }
    }
}
